### ISSUE TITLE
Move DB config files

### ISSUE THREAD

**Issue by antoinecampbell** [Yeti-Robotics/angular-scouting#3]
- Move config file to separate folder so we can copy over new versions of the site easily

**Comment by antoinecampbell** [comment]
Sam, create a directory at the same level as the php/ folder like config/ and place the config.php file in there. When we copy the site over to the server we can ignore that folder or we can just set that folder to read only so it doesn't accidentally get overwritten.

**Comment by samperlmutter** [comment]
Just committed and updated the site with a config directory and made it read only.
